#!/usr/bin/env python3
"""
Assign semantic labels to SAM-generated object masks using CLIP.
This script reads the multiview-consistent masks generated by generate_multiview_sam_masks.py
and assigns a semantic category (from a user-provided list) to each object_id.

Output: a JSON file mapping object_id to category and confidence.
"""

import os
import sys
# Set LD_LIBRARY_PATH to include torch libs
torch_lib = os.path.join(sys.prefix, 'lib', 'python{}.{}'.format(sys.version_info.major, sys.version_info.minor), 'site-packages', 'torch', 'lib')
if os.path.exists(torch_lib):
    os.environ['LD_LIBRARY_PATH'] = torch_lib + ':' + os.environ.get('LD_LIBRARY_PATH', '')
import json
import argparse
import glob
from collections import defaultdict
from dataclasses import dataclass
from concurrent.futures import ThreadPoolExecutor, wait, FIRST_COMPLETED, as_completed
from typing import Dict, List, Tuple, Optional

import numpy as np
from PIL import Image
import torch
import torch.nn.functional as F
from tqdm import tqdm

try:
    import clip
    CLIP_AVAILABLE = True
except ImportError:
    CLIP_AVAILABLE = False
    print("Warning: clip package not installed. Please install via: pip install openai-clip")

def load_clip_model(device="cuda", model_name="ViT-B/32"):
    """Load CLIP model and preprocessing function."""
    if not CLIP_AVAILABLE:
        raise ImportError("clip package not available. Install with: pip install openai-clip")
    model, preprocess = clip.load(model_name, device=device)
    return model, preprocess

def get_text_features(model, categories: List[str], device="cuda") -> torch.Tensor:
    """Compute CLIP text features for a list of category names."""
    text_inputs = clip.tokenize(categories).to(device)
    with torch.no_grad():
        text_features = model.encode_text(text_inputs)
        text_features = F.normalize(text_features, dim=-1)
    return text_features

def extract_mask_features(
    model, preprocess, image_path: str, mask: np.ndarray, device="cuda"
) -> Optional[torch.Tensor]:
    """Extract CLIP image feature for the region defined by mask.
    
    Args:
        model: CLIP model
        preprocess: CLIP preprocessing function
        image_path: path to RGB image
        mask: binary mask (H,W) where 1 indicates object region
        device: compute device
        
    Returns:
        CLIP feature vector (normalized) or None if mask is empty.
    """
    # Load image
    img = Image.open(image_path).convert("RGB")
    img_arr = np.array(img)
    if img_arr.shape[:2] != mask.shape:
        # Resize mask to image size if needed (should match already)
        from PIL import Image as PILImage
        mask_pil = PILImage.fromarray(mask).resize((img_arr.shape[1], img_arr.shape[0]), resample=Image.NEAREST)
        mask = np.array(mask_pil)
    
    # Check mask area
    if mask.sum() < 10:  # too small
        return None
    
    # Crop image to mask bounding box
    rows, cols = np.where(mask > 0)
    if len(rows) == 0:
        return None
    rmin, rmax = rows.min(), rows.max()
    cmin, cmax = cols.min(), cols.max()
    # Expand bbox slightly (10%)
    h, w = mask.shape
    pad_h = int((rmax - rmin) * 0.1)
    pad_w = int((cmax - cmin) * 0.1)
    rmin = max(0, rmin - pad_h)
    rmax = min(h-1, rmax + pad_h)
    cmin = max(0, cmin - pad_w)
    cmax = min(w-1, cmax + pad_w)
    
    crop = img_arr[rmin:rmax+1, cmin:cmax+1]
    if crop.size == 0:
        return None
    
    # Apply mask to crop (optional: we can feed masked crop or full crop)
    # Here we feed the full crop; mask is already used for bbox.
    crop_pil = Image.fromarray(crop)
    try:
        preprocessed = preprocess(crop_pil).unsqueeze(0).to(device)
    except Exception as e:
        print(f"  Warning: preprocessing failed for {image_path}: {e}")
        return None
    
    with torch.no_grad():
        image_features = model.encode_image(preprocessed)
        image_features = F.normalize(image_features, dim=-1)
    return image_features.squeeze(0)  # (512,)


@dataclass(frozen=True)
class MaskItem:
    stem: str
    mask_path: str
    area: int
    bbox: Tuple[int, int, int, int]
    mask_size: Tuple[int, int]


def _compute_padded_bbox(mask: np.ndarray) -> Optional[Tuple[int, int, int, int]]:
    rows, cols = np.where(mask > 0)
    if rows.size == 0:
        return None
    rmin, rmax = int(rows.min()), int(rows.max())
    cmin, cmax = int(cols.min()), int(cols.max())

    h, w = mask.shape[:2]
    pad_h = int((rmax - rmin) * 0.1)
    pad_w = int((cmax - cmin) * 0.1)
    rmin = max(0, rmin - pad_h)
    rmax = min(h - 1, rmax + pad_h)
    cmin = max(0, cmin - pad_w)
    cmax = min(w - 1, cmax + pad_w)
    return rmin, rmax, cmin, cmax


def _resolve_image_path(image_dir: str, stem: str) -> Optional[str]:
    image_path = os.path.join(image_dir, f"{stem}.jpg")
    if os.path.exists(image_path):
        return image_path
    for ext in [".png", ".JPG", ".jpeg"]:
        alt = os.path.join(image_dir, f"{stem}{ext}")
        if os.path.exists(alt):
            return alt
    return None


def _preprocess_crop(
    preprocess,
    image_path: str,
    bbox: Tuple[int, int, int, int],
    mask_size: Tuple[int, int],
) -> Optional[torch.Tensor]:
    try:
        img = Image.open(image_path).convert("RGB")
    except Exception:
        return None

    h_img, w_img = img.height, img.width
    h_mask, w_mask = mask_size
    rmin, rmax, cmin, cmax = bbox

    if (h_img, w_img) != (h_mask, w_mask) and h_mask > 0 and w_mask > 0:
        scale_y = h_img / h_mask
        scale_x = w_img / w_mask
        rmin = int(round(rmin * scale_y))
        rmax = int(round(rmax * scale_y))
        cmin = int(round(cmin * scale_x))
        cmax = int(round(cmax * scale_x))

    rmin = max(0, min(rmin, h_img - 1))
    rmax = max(0, min(rmax, h_img - 1))
    cmin = max(0, min(cmin, w_img - 1))
    cmax = max(0, min(cmax, w_img - 1))
    if rmax < rmin or cmax < cmin:
        return None

    crop = img.crop((cmin, rmin, cmax + 1, rmax + 1))
    try:
        return preprocess(crop)
    except Exception:
        return None


def process_mask_file(mf, stem, min_mask_area):
    fname = os.path.basename(mf)
    # parse obj_id
    try:
        obj_id = int(fname.split("_")[1].split(".")[0])
    except (IndexError, ValueError):
        return None

    try:
        mask_img = Image.open(mf).convert("L")
        mask_arr = np.array(mask_img) > 127
    except Exception:
        return None

    area = mask_arr.sum()
    if area < min_mask_area:
        return None

    bbox = _compute_padded_bbox(mask_arr)
    if bbox is None:
        return None

    return obj_id, MaskItem(
        stem=stem,
        mask_path=mf,
        area=int(area),
        bbox=bbox,
        mask_size=mask_arr.shape[:2],
    )



def main():
    parser = argparse.ArgumentParser(description="Assign semantic labels to SAM masks using CLIP")
    parser.add_argument("--source_path", required=True, help="Dataset root (contains images/ and masks_sam/)")
    parser.add_argument("--images_subdir", default="images_4", help="Subdirectory containing images (relative to source_path)")
    parser.add_argument("--mask_subdir", default=os.path.join("images_4", "masks_sam"),
                        help="Subdirectory containing SAM masks (relative to source_path)")
    parser.add_argument("--categories", required=True,
                        help="Comma-separated list of category names, e.g., 'chair,table,person,car'")
    parser.add_argument("--output_labels", default="labels.json",
                        help="Output JSON file name (will be placed inside mask_subdir)")
    parser.add_argument("--clip_model", default="ViT-B/32", help="CLIP model name (e.g., ViT-B/32, ViT-L/14)")
    parser.add_argument("--device", default="cuda", help="Device: cuda or cpu")
    parser.add_argument("--max_images_per_object", type=int, default=5,
                        help="Max number of views to consider for each object (to save computation)")
    parser.add_argument("--min_mask_area", type=int, default=100,
                        help="Minimum mask area (pixels) to consider for feature extraction")
    parser.add_argument("--batch_size", type=int, default=64,
                        help="Batch size for CLIP image encoding")
    parser.add_argument("--num_workers", type=int, default=8,
                        help="Thread workers for image loading/cropping/preprocess")
    parser.add_argument("--prefetch", type=int, default=256,
                        help="How many crops to prefetch in the thread pool")
    args = parser.parse_args()
    
    if not CLIP_AVAILABLE:
        print("Error: clip package not installed. Please install via: pip install openai-clip")
        sys.exit(1)
    
    # Paths
    image_dir = os.path.join(args.source_path, args.images_subdir)
    mask_root = os.path.join(args.source_path, args.mask_subdir)
    output_path = os.path.join(mask_root, args.output_labels)
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    if not os.path.isdir(mask_root):
        print(f"Error: mask directory not found: {mask_root}")
        sys.exit(1)
    
    # Parse categories
    categories = [c.strip() for c in args.categories.split(",") if c.strip()]
    if len(categories) == 0:
        print("Error: no categories provided")
        sys.exit(1)
    print(f"Categories: {categories}")
    
    # Load CLIP
    print(f"Loading CLIP model {args.clip_model}...")
    device = args.device if torch.cuda.is_available() and args.device == "cuda" else "cpu"
    model, preprocess = load_clip_model(device=device, model_name=args.clip_model)
    text_features = get_text_features(model, categories, device=device).cpu()  # (N_cat, D) normalized
    
    # Gather all object IDs and their associated masks across views
    # Structure: object_id -> list of (image_stem, mask_path, area)
    object_mask_map = defaultdict(list)
    
    # List all image stem directories under mask_root
    stem_dirs = [d for d in glob.glob(os.path.join(mask_root, "*")) if os.path.isdir(d)]
    print(f"Found {len(stem_dirs)} view directories")
    
    # for stem_dir in tqdm(stem_dirs, desc="Processing view directories"):
    #     stem = os.path.basename(stem_dir)
    #     mask_files = glob.glob(os.path.join(stem_dir, "obj_*.png"))
    #     for mf in mask_files:
    #         fname = os.path.basename(mf)
    #         # Parse object_id from filename "obj_XXXX.png"
    #         try:
    #             obj_id = int(fname.split("_")[1].split(".")[0])
    #         except (IndexError, ValueError):
    #             continue
    #         # Load mask to compute area
    #         mask_img = Image.open(mf).convert("L")  # 转为灰度图，单通道

    #         # mask覆盖像素面积，单位为像素
    #         mask_arr = np.array(mask_img) > 127
    #         area = mask_arr.sum()
    #         if area < args.min_mask_area:
    #             continue
    #         bbox = _compute_padded_bbox(mask_arr)
    #         if bbox is None:
    #             continue
    #         object_mask_map[obj_id].append(
    #             MaskItem(stem=stem, mask_path=mf, area=int(area), bbox=bbox, mask_size=mask_arr.shape[:2])
    #         )
    object_mask_map = defaultdict(list)
    num_workers = args.num_workers if args.num_workers > 0 else 8
    with ThreadPoolExecutor(max_workers=num_workers) as executor:
        futures = []
        for stem_dir in stem_dirs:
            stem = os.path.basename(stem_dir)
            mask_files = glob.glob(os.path.join(stem_dir, "obj_*.png"))
            for mf in mask_files:
                futures.append(
                    executor.submit(process_mask_file, mf, stem, args.min_mask_area)
                )
        for fut in tqdm(as_completed(futures), total=len(futures), desc="Processing masks"):
            res = fut.result()
            if res is None:
                continue
            obj_id, item = res
            object_mask_map[obj_id].append(item)
    print(f"Found {len(object_mask_map)} unique object IDs")
    
    
    # For each object, select up to max_images_per_object views (largest masks first) and compute average CLIP feature
    object_labels = {}
    selected_tasks: List[Tuple[int, MaskItem]] = []
    for obj_id, items in object_mask_map.items():
        items_sorted = sorted(items, key=lambda x: x.area, reverse=True)
        selected = items_sorted[: args.max_images_per_object]
        for item in selected:
            selected_tasks.append((obj_id, item))

    features_by_obj: Dict[int, List[torch.Tensor]] = defaultdict(list)
    batch: List[Tuple[int, torch.Tensor]] = []
    def flush_batch():
        nonlocal batch
        if len(batch) == 0:
            return
        obj_ids = [obj_id for obj_id, _ in batch]
        tensor_batch = torch.stack([t for _, t in batch], dim=0).to(device)
        with torch.no_grad():
            feats = model.encode_image(tensor_batch)
            feats = F.normalize(feats, dim=-1).cpu()
        for obj_id, feat in zip(obj_ids, feats):
            features_by_obj[obj_id].append(feat)
        batch = []

    if args.num_workers <= 0:
        pbar = tqdm(selected_tasks, desc="Extracting CLIP features", unit="crop")
        for obj_id, item in pbar:
            image_path = _resolve_image_path(image_dir, item.stem)
            if image_path is None:
                continue
            crop_tensor = _preprocess_crop(preprocess, image_path, item.bbox, item.mask_size)
            if crop_tensor is None:
                continue
            batch.append((obj_id, crop_tensor))
            if len(batch) >= args.batch_size:
                flush_batch()
        flush_batch()
        pbar.close()
    else:
        pending = {}
        task_iter = iter(selected_tasks)
        total_crops = len(selected_tasks)
        pbar = tqdm(total=total_crops, desc="Extracting CLIP features", unit="crop")
        with ThreadPoolExecutor(max_workers=args.num_workers) as pool:
            while len(pending) < args.prefetch:
                try:
                    obj_id, item = next(task_iter)
                except StopIteration:
                    break
                image_path = _resolve_image_path(image_dir, item.stem)
                if image_path is None:
                    pbar.update(1)
                    continue
                fut = pool.submit(_preprocess_crop, preprocess, image_path, item.bbox, item.mask_size)
                pending[fut] = obj_id

            while pending:
                done, _ = wait(pending.keys(), return_when=FIRST_COMPLETED)
                for fut in done:
                    obj_id = pending.pop(fut)
                    pbar.update(1)
                    try:
                        crop_tensor = fut.result()
                    except Exception:
                        crop_tensor = None
                    if crop_tensor is not None:
                        batch.append((obj_id, crop_tensor))
                        if len(batch) >= args.batch_size:
                            flush_batch()

                while len(pending) < args.prefetch:
                    try:
                        obj_id, item = next(task_iter)
                    except StopIteration:
                        break
                    image_path = _resolve_image_path(image_dir, item.stem)
                    if image_path is None:
                        pbar.update(1)
                        continue
                    fut = pool.submit(_preprocess_crop, preprocess, image_path, item.bbox, item.mask_size)
                    pending[fut] = obj_id

        flush_batch()
        pbar.close()

    pbar = tqdm(object_mask_map.keys(), desc="Assigning labels", unit="obj")
    for obj_id in pbar:
        features = features_by_obj.get(obj_id, [])
        if len(features) == 0:
            object_labels[obj_id] = {"category": "unknown", "confidence": 0.0}
            continue

        avg_feature = torch.stack(features).mean(dim=0)
        avg_feature = F.normalize(avg_feature.unsqueeze(0), dim=-1).squeeze(0)

        with torch.no_grad():
            sim = (avg_feature @ text_features.T).numpy()
        best_idx = int(np.argmax(sim))
        confidence = float(sim[best_idx])
        category = categories[best_idx]

        object_labels[obj_id] = {"category": category, "confidence": confidence}
        pbar.set_postfix({"obj_id": obj_id, "category": category, "confidence": f"{confidence:.3f}"})
    pbar.close()
    
    # Save labels
    with open(output_path, "w") as f:
        json.dump(object_labels, f, indent=2)
    print(f"Labels saved to {output_path}")
    
    # Also generate a summary CSV for easy viewing
    csv_path = os.path.join(mask_root, "labels_summary.csv")
    with open(csv_path, "w") as f:
        f.write("object_id,category,confidence\n")
        for obj_id, info in sorted(object_labels.items()):
            f.write(f"{obj_id},{info['category']},{info['confidence']:.4f}\n")
    print(f"Summary CSV saved to {csv_path}")

if __name__ == "__main__":
    main()
